### ISSUE TITLE
Hello! The color of the table border is inconsistent, please fix it. 

### ISSUE THREAD

**Issue by zhouxinghong** [kinmury/obsidian-ukiyo#11]
Hello! The color of the table border is inconsistent, please fix it. Thanks!
System: Win10
Version: 2.1.2
![2023-02-23_174018](https://user-images.githubusercontent.com/54253524/220871410-e6edfd07-d327-485e-8c8d-07389f2dc87f.png)
![2023-02-23_173849](https://user-images.githubusercontent.com/54253524/220871421-cb90de32-c573-4e52-8f2b-e058f3a28e56.png)
![2023-02-23_173746](https://user-images.githubusercontent.com/54253524/220871425-30a2f9a0-26e9-4964-ac92-c184f0745ccf.png)

**Comment by kinmury** [comment]
Thank you for the issue and for your patience. I just pushed the new rework version of the theme. Now it should work.
Once again, thank you and I hope you enjoy the new version 😁
