### ISSUE TITLE
Way to change the text on the background with no windows open?

### ISSUE THREAD

**Issue by Rayquaza1090** [kinmury/obsidian-ukiyo#13]
See title. I thought the image attached that was the default image if no windows were open was pretty charming, but I was curious if I would be able to change it to something else. I am quite poor at coding and don't know where I would go to modify it.

![r8krxDl](https://github.com/kinmury/obsidian-ukiyo/assets/46958809/23fcd684-84bc-4af5-80f1-98655a145e74)

**Comment by richardscull** [comment]
@Rayquaza1090 Hey! Answering if you're still curious about this.

It's quite easy to edit the text and even emoji. Just open directory with your obsidian vault, go to `.obsidian/themes/Ukiyo` and open theme.css.

![image](https://github.com/kinmury/obsidian-ukiyo/assets/106016833/6dc7b3c8-8f24-496d-b4e5-496f4c927967)


 After that using search in any text editor find "All I need is" and you can edit this text to anything you want it to be. Just below is emoji, so you can edit to too :)

![image](https://github.com/kinmury/obsidian-ukiyo/assets/106016833/b240a024-ca10-488e-bdd1-133adb7f93e1)

**Comment by Rayquaza1090** [comment]
@richardscull Sorry it took me so long to respond! I greatly appreciate it. I'm not too familiar with this sort of stuff, but I'm very thankful you helped me out. Have a blessed day.

**Comment by Rayquaza1090** [comment]
@richardscull Sorry it took me so long to respond! I greatly appreciate it. I'm not too familiar with this sort of stuff, but I'm very thankful you helped me out. Have a blessed day.
