### ISSUE TITLE
Text Center - `force-center`

### ISSUE THREAD

**Issue by EnriqueBravo115** [kinmury/obsidian-ukiyo#4]
I love your theme but now the text is left to right, i love the text in center for make presentations

**Comment by kinmury** [comment]
Hello there 😄, I'm glad that you enjoy the theme 😊

I'm not sure what do you mean by *"now is left to right"*. I mean... *it always has been* (??).

Anyway, I think I've got a solution for your problem. Knowing that not everyone would use Obsidian with all the text in the center, I'm gonna add a new `cssClass` called `force-center`, which will make every element of that page (headings, paragraphs, images (those are already center), graphs, ...) to appear centered.

I hope that this will fix your issue, but if I didn't understand your request, please let me know 😉

**Comment by kinmury** [comment]
Hi @EnriqueBravo115,

I've published a release with the `cssClass` mentioned before. Please check that it works as you wanted and, if there is no issue, then I'll close this on the next release.

Thank you for your patience😊

**Comment by EnriqueBravo115** [comment]
ok bro i check that

**Comment by kinmury** [comment]
Since there is no more comments about this issue, I'll be closing it.
If there is an issue with it, open it again
