### ISSUE TITLE
LaTeX Binomial not displaying correctly 

### ISSUE THREAD

**Issue by Crusher50** [kinmury/obsidian-ukiyo#7]
When I create a binomial using LaTeX it is displayed incorrectly with the top coefficient appearing outside of the brackets.

  
![image](https://user-images.githubusercontent.com/91010433/215482088-b3078f5e-63e4-4a6d-9404-5ed9aa57cd68.png)

**Comment by kinmury** [comment]
Thank you for opening the issue :D
I just pushed the fix so I'm closing the issue. 
Let me know if anything else doesn't work as well.
