### ISSUE TITLE
Selected /  interactive buttons are opaque in Golden Coffee light mode

### ISSUE THREAD

**Issue by Crusher50** [kinmury/obsidian-ukiyo#8]
Selected /  interactive buttons are opaque in Golden Coffee light mode, this causes some elements to be unreadable unless the mouse is hovering over the button. 

This also affects the vim cursor when typing.

![image](https://user-images.githubusercontent.com/91010433/215733452-66628078-2b55-4bf6-86e9-76e60ddba1ae.png)

![image](https://user-images.githubusercontent.com/91010433/215733571-7bbd5974-22c4-440f-811f-4753c77e872b.png)

![image](https://user-images.githubusercontent.com/91010433/215733524-0dc977c5-1bab-4d01-b209-670f507fb544.png)

![image](https://user-images.githubusercontent.com/91010433/215733762-8260a50f-5f68-4676-a61b-0d7b836a1bb8.png)

**Comment by kinmury** [comment]
Thank you for telling about all these issues. They are fixed now, hope you can enjoy it properly now ;P
