### ISSUE TITLE
Side dock ribbon artifact in partially hidden mode

### ISSUE THREAD

**Issue by Crusher50** [kinmury/obsidian-ukiyo#9]
When the side dock is set to partially hidden there is an artifact of what appears to be a part of the separator line left over; when the side dock is not actively being viewed, as shown here:

![image](https://user-images.githubusercontent.com/91010433/215734410-89d90927-1fcb-472f-b430-a71e455f39ad.png)

Unfolded Side dock:

![image](https://user-images.githubusercontent.com/91010433/215734482-040116b7-e8b6-41e5-aec3-389c32fff0f2.png)

**Comment by kinmury** [comment]
Thank you for telling about all these issues. They are fixed now, hope you can enjoy it properly now ;P - Part 2

**Comment by Crusher50** [comment]
Cool, thanks for the work you've done on this theme!
